/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_moodweather_android_ndk_NDK */

#ifndef _Included_com_moodweather_android_ndk_NDK
#define _Included_com_moodweather_android_ndk_NDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_moodweather_android_ndk_NDK
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_moodweather_android_ndk_NDK_getStringFromNative
  (JNIEnv *, jclass);

/*
 * Class:     com_moodweather_android_ndk_NDK
 * Method:    getString_From_c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_moodweather_android_ndk_NDK_getString_1From_1c
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
